version: '3.8'

services:
  apache-php:
    build: ./apache-php
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - lampnet

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - lampnet

networks:
  lampnet:
    driver: bridge

