apiVersion: apps/v1
kind: Deployment
metadata:
  name: lamp-app
spec:
  selector:
    matchLabels:
      app: lamp
  replicas: 1
  template:
    metadata:
      labels:
        app: lamp
    spec:
      containers:
      - name: lamp
        image: harshsunilchavan/lamp-app:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: lamp-service
spec:
  type: NodePort
  selector:
    app: lamp
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007


